import {
  Document,
  Page,
  View,
  Text,
  StyleSheet,
  Svg,
  Path,
  Line,
  Polyline,
  Circle,
  Text as SvgText,
} from '@react-pdf/renderer';

const BRAND_GREEN = '#2E8B5F';
const BRAND_GREEN_SOFT = '#7DBA8A';
const GREEN_TINT = '#ECF2ED';
const INK = '#0F2A22';
const TITLE_INK = '#0F2A22';
const STONE = '#6B7066';
const RULE = '#DDD7CB';
const PAPER_WARM = '#FAF8F2';
const AMBER = '#BA7517';
const TARGET_RED = '#D85A30';
const LOSS_GREEN = '#2E8B5F';
const GAIN_RED = '#D85A30';

const styles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 40,
    paddingLeft: 36,
    paddingRight: 36,
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: INK,
    backgroundColor: '#FFFFFF',
  },

  // Header band (full-bleed via negative margins)
  headerBand: {
    backgroundColor: BRAND_GREEN,
    height: 72,
    marginTop: -40,
    marginLeft: -36,
    marginRight: -36,
    paddingLeft: 36,
    paddingRight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandRow: { flexDirection: 'row', alignItems: 'center' },
  headerRight: { alignItems: 'flex-end' },
  headerClient: {
    color: '#FFFFFF',
    fontFamily: 'Helvetica-Bold',
    fontSize: 18,
    letterSpacing: -0.3,
  },
  headerSub: { color: '#FFFFFF', opacity: 0.75, fontSize: 12, marginTop: 3 },
  headerDate: { color: '#FFFFFF', opacity: 0.6, fontSize: 10, marginTop: 2 },

  // Client info bar
  infoBar: {
    backgroundColor: GREEN_TINT,
    marginLeft: -36,
    marginRight: -36,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 36,
    paddingRight: 36,
    marginBottom: 18,
  },
  infoText: { fontSize: 11, color: STONE },

  sectionTitle: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 13,
    color: TITLE_INK,
    marginBottom: 8,
  },

  // Goal progress two-column
  goalRow: { flexDirection: 'row', marginBottom: 18 },
  goalLeft: { width: '55%', paddingRight: 16 },
  goalRight: { width: '45%' },

  barLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  barLabel: { fontSize: 10, color: STONE },
  barPct: { fontSize: 10, fontFamily: 'Helvetica-Bold', color: INK },
  barTrack: {
    height: 10,
    backgroundColor: '#DDD7CB',
    borderRadius: 5,
    overflow: 'hidden',
  },
  barFill: { height: 10, borderRadius: 5 },
  barEndsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 3,
  },
  barEnd: { fontSize: 9, color: STONE },

  statLine: { fontSize: 11, color: INK, marginTop: 6 },
  statLost: { fontSize: 12, fontFamily: 'Helvetica-Bold', color: BRAND_GREEN, marginTop: 8 },

  pill: {
    marginTop: 10,
    alignSelf: 'flex-start',
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 9,
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
  },

  targetRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 10,
    paddingRight: 10,
  },
  targetRowAlt: { backgroundColor: PAPER_WARM },
  targetLabel: { fontSize: 9, color: STONE },
  targetValue: { fontSize: 12, fontFamily: 'Helvetica-Bold', color: INK },

  // Chart
  chartLegendRow: { flexDirection: 'row', marginTop: 6 },
  legendItem: { flexDirection: 'row', alignItems: 'center', marginRight: 16 },
  legendSwatch: { width: 14, height: 2, marginRight: 5 },
  legendText: { fontSize: 9, color: STONE },

  // Table
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: BRAND_GREEN,
    paddingTop: 5,
    paddingBottom: 5,
  },
  th: {
    fontSize: 9,
    color: '#FFFFFF',
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    paddingLeft: 4,
    paddingRight: 4,
  },
  tableRow: {
    flexDirection: 'row',
    paddingTop: 5,
    paddingBottom: 5,
    borderBottomWidth: 0.5,
    borderBottomColor: RULE,
  },
  tableRowAlt: { backgroundColor: PAPER_WARM },
  td: { fontSize: 9, color: INK, paddingLeft: 4, paddingRight: 4 },
  tableNote: { fontSize: 9, color: STONE, fontStyle: 'italic', marginTop: 5 },

  // Footer
  footer: {
    position: 'absolute',
    bottom: 18,
    left: 36,
    right: 36,
    paddingTop: 6,
    borderTopWidth: 0.5,
    borderTopColor: RULE,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerText: { fontSize: 10, color: STONE },
});

// Column widths: Date | Weight | Change | Waist | Hips | Arms | Notes
const COL = { date: 70, weight: 55, change: 50, waist: 45, hips: 45, arms: 45 };

const DEFAULT_LABELS = {
  progressReport: 'Progress Report',
  goalProgress: 'Goal Progress',
  visitHistory: 'Visit History',
  targets: 'Targets',
  generatedBy: 'Generated by NutriTrack',
  actualWeight: 'Actual weight',
  target: 'Target',
  onTrack: 'On track',
  behind: 'Behind',
  noGoalSet: 'No goal set',
  memberSince: 'Member since',
  date: 'Date',
  weight: 'Weight',
  change: 'Change',
  notes: 'Notes',
  goalProgressBar: 'Goal progress',
  dailyCalories: 'Daily calories',
  protein: 'Protein',
  carbs: 'Carbs',
  fat: 'Fat',
  kgLost: 'kg lost',
  kgToGo: 'kg to go',
  targetDate: 'Target date',
  daysRemaining: 'Days remaining',
  showingLast: 'Showing last 20 visits',
};

function num(v) {
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

function fmtDate(iso) {
  if (!iso) return '—';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return String(iso);
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function fmtCm(v) {
  const n = num(v);
  return n != null ? `${n} cm` : '—';
}

export default function ProgressReportPDF({
  client = {},
  goal = null,
  logs = [],
  logSummary = null,
  generatedDate = '',
  labels: labelsProp,
}) {
  const labels = { ...DEFAULT_LABELS, ...(labelsProp || {}) };

  // Normalize ordering. Chart needs ascending by log_date; table newest first.
  const byDateAsc = [...logs].sort(
    (a, b) => new Date(a.log_date).getTime() - new Date(b.log_date).getTime()
  );
  const byDateDesc = [...byDateAsc].reverse();

  const startWeight = num(client.start_weight);
  const targetWeight = goal ? num(goal.target_weight) : null;
  const latestWeight =
    byDateAsc.length > 0 ? num(byDateAsc[byDateAsc.length - 1].weight) : startWeight;

  const progressPct =
    logSummary?.progress_pct != null ? Math.max(0, Math.min(100, Number(logSummary.progress_pct))) : 0;
  const totalLost = logSummary?.total_lost != null ? Number(logSummary.total_lost) : null;
  const remaining =
    latestWeight != null && targetWeight != null
      ? Math.max(0, latestWeight - targetWeight)
      : null;

  let daysRemaining = null;
  if (goal?.target_date) {
    const td = new Date(goal.target_date);
    if (!Number.isNaN(td.getTime())) {
      daysRemaining = Math.max(0, Math.ceil((td.getTime() - Date.now()) / 86400000));
    }
  }

  // Pace: compare progress vs. elapsed time toward the target date.
  let onTrack = progressPct >= 50;
  if (client.created_at && goal?.target_date) {
    const start = new Date(client.created_at).getTime();
    const end = new Date(goal.target_date).getTime();
    if (Number.isFinite(start) && Number.isFinite(end) && end > start) {
      const elapsedPct = Math.max(0, Math.min(100, ((Date.now() - start) / (end - start)) * 100));
      onTrack = progressPct >= elapsedPct;
    }
  }

  const barFillColor = progressPct >= 50 ? BRAND_GREEN : AMBER;

  // ---- Chart geometry ----
  const weights = byDateAsc.map((l) => num(l.weight)).filter((w) => w != null);
  const hasChart = weights.length >= 1;
  const minW = hasChart
    ? Math.min(...weights, targetWeight != null ? targetWeight : weights[0]) - 2
    : 0;
  const maxW = hasChart ? Math.max(...weights) + 2 : 0;
  const chartWidth = 450; // 490 - 40
  const chartHeight = 90; // 100 - 10
  const span = maxW - minW || 1;
  const toY = (w) => 100 - ((w - minW) / span) * chartHeight;
  const toX = (i) => (byDateAsc.length <= 1 ? 40 : 40 + (i / (byDateAsc.length - 1)) * chartWidth);

  const points = byDateAsc
    .map((l, i) => {
      const w = num(l.weight);
      return w != null ? `${toX(i)},${toY(w)}` : null;
    })
    .filter(Boolean);
  const pointsString = points.join(' ');
  const targetY = targetWeight != null ? toY(targetWeight) : null;

  // ---- Table: newest first, cap at 20 ----
  const tableLogs = byDateDesc.slice(0, 20);
  const truncated = byDateDesc.length > 20;

  return (
    <Document
      title={`${client?.name || 'Client'} — ${labels.progressReport}`}
      author="NutriTrack"
      subject="Client progress report"
    >
      <Page size="A4" orientation="portrait" style={styles.page}>
        {/* SECTION 1 — HEADER */}
        <View style={styles.headerBand} fixed>
          <View style={styles.brandRow}>
            <Svg viewBox="0 0 620 180" style={{ width: 160, height: 46 }}>
              <Path
                d="M 30 120 L 150 120 L 168 96 L 188 140 L 208 108 L 224 120 L 590 120"
                stroke="#7DBA8A"
                strokeWidth="3"
                strokeLinecap="round"
                strokeLinejoin="round"
                fill="none"
              />
              <SvgText
                x="30"
                y="100"
                fontFamily="Helvetica-Bold"
                fontSize="84"
                fill="#F4F1EA"
                letterSpacing="-3"
              >
                NutriTrack
              </SvgText>
              <Path
                d="M 258 42 C 258 32, 266 26, 274 26 C 274 36, 268 44, 258 42 Z"
                fill="#7DBA8A"
              />
            </Svg>
          </View>
          <View style={styles.headerRight}>
            <Text style={styles.headerClient}>{client?.name || 'Client'}</Text>
            <Text style={styles.headerSub}>{labels.progressReport}</Text>
            {generatedDate ? <Text style={styles.headerDate}>{generatedDate}</Text> : null}
          </View>
        </View>

        <View style={{ height: 16 }} />

        {/* SECTION 2 — CLIENT INFO BAR */}
        <View style={styles.infoBar}>
          <Text style={styles.infoText}>
            {[
              client.age != null ? `Age: ${client.age}` : null,
              client.gender ? `Gender: ${client.gender}` : null,
              client.height_cm != null ? `Height: ${client.height_cm} cm` : null,
              client.start_weight != null ? `Start weight: ${client.start_weight} kg` : null,
              client.created_at ? `${labels.memberSince}: ${fmtDate(client.created_at)}` : null,
            ]
              .filter(Boolean)
              .join('   ·   ')}
          </Text>
        </View>

        {/* SECTION 3 — GOAL PROGRESS */}
        <View style={styles.goalRow} wrap={false}>
          {/* Left column */}
          <View style={styles.goalLeft}>
            <Text style={styles.sectionTitle}>{labels.goalProgress}</Text>

            {goal ? (
              <>
                <View style={styles.barLabelRow}>
                  <Text style={styles.barLabel}>{labels.goalProgressBar}</Text>
                  <Text style={styles.barPct}>{Math.round(progressPct)}%</Text>
                </View>
                <View style={styles.barTrack}>
                  <View
                    style={[
                      styles.barFill,
                      { width: `${progressPct}%`, backgroundColor: barFillColor },
                    ]}
                  />
                </View>
                <View style={styles.barEndsRow}>
                  <Text style={styles.barEnd}>
                    {startWeight != null ? `${startWeight} kg` : '—'}
                  </Text>
                  <Text style={styles.barEnd}>
                    {targetWeight != null ? `${targetWeight} kg` : '—'}
                  </Text>
                </View>

                {totalLost != null ? (
                  <Text style={styles.statLost}>
                    {totalLost.toFixed(1)} {labels.kgLost}
                  </Text>
                ) : null}
                {remaining != null ? (
                  <Text style={styles.statLine}>
                    {remaining.toFixed(1)} {labels.kgToGo}
                  </Text>
                ) : null}
                <Text style={styles.statLine}>
                  {labels.targetDate}: {fmtDate(goal.target_date)}
                </Text>
                {daysRemaining != null ? (
                  <Text style={styles.statLine}>
                    {labels.daysRemaining}: {daysRemaining}
                  </Text>
                ) : null}

                <Text
                  style={[
                    styles.pill,
                    onTrack
                      ? { backgroundColor: GREEN_TINT, color: BRAND_GREEN }
                      : { backgroundColor: '#FBEFD9', color: AMBER },
                  ]}
                >
                  {onTrack ? labels.onTrack : labels.behind}
                </Text>
              </>
            ) : (
              <Text style={styles.statLine}>{labels.noGoalSet}</Text>
            )}
          </View>

          {/* Right column */}
          <View style={styles.goalRight}>
            <Text style={styles.sectionTitle}>{labels.targets}</Text>
            {[
              { label: labels.dailyCalories, value: goal?.daily_calories != null ? `${goal.daily_calories} kcal` : '—' },
              { label: labels.protein, value: goal?.protein_g != null ? `${goal.protein_g} g` : '—' },
              { label: labels.carbs, value: goal?.carbs_g != null ? `${goal.carbs_g} g` : '—' },
              { label: labels.fat, value: goal?.fat_g != null ? `${goal.fat_g} g` : '—' },
            ].map((row, i) => (
              <View key={row.label} style={[styles.targetRow, i % 2 === 1 && styles.targetRowAlt]}>
                <Text style={styles.targetLabel}>{row.label}</Text>
                <Text style={styles.targetValue}>{row.value}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* SECTION 4 — WEIGHT CHART */}
        {hasChart ? (
          <View wrap={false} style={{ marginBottom: 18 }}>
            <Text style={styles.sectionTitle}>{labels.actualWeight}</Text>
            <Svg viewBox="0 0 500 120" style={{ width: '100%', height: 120 }}>
              {/* Y axis */}
              <Line x1="40" y1="10" x2="40" y2="100" stroke={RULE} strokeWidth="0.5" />
              {/* X axis */}
              <Line x1="40" y1="100" x2="490" y2="100" stroke={RULE} strokeWidth="0.5" />

              {/* Target line */}
              {targetY != null ? (
                <Line
                  x1="40"
                  y1={targetY}
                  x2="490"
                  y2={targetY}
                  stroke={TARGET_RED}
                  strokeWidth="0.8"
                  strokeDasharray="4,3"
                />
              ) : null}

              {/* Weight line */}
              {points.length >= 2 ? (
                <Polyline
                  points={pointsString}
                  fill="none"
                  stroke={BRAND_GREEN}
                  strokeWidth="1.5"
                  strokeLinejoin="round"
                  strokeLinecap="round"
                />
              ) : null}

              {/* Dots */}
              {byDateAsc.map((l, i) => {
                const w = num(l.weight);
                if (w == null) return null;
                return (
                  <Circle
                    key={l.id ?? i}
                    cx={toX(i)}
                    cy={toY(w)}
                    r={i === byDateAsc.length - 1 ? 5 : 3}
                    fill={BRAND_GREEN}
                  />
                );
              })}

              {/* Y axis labels */}
              <SvgText x="36" y={toY(maxW) + 3} fontSize="7" fill={STONE} textAnchor="end">
                {maxW.toFixed(0)}
              </SvgText>
              <SvgText x="36" y={toY((maxW + minW) / 2) + 3} fontSize="7" fill={STONE} textAnchor="end">
                {((maxW + minW) / 2).toFixed(0)}
              </SvgText>
              <SvgText x="36" y={toY(minW) + 3} fontSize="7" fill={STONE} textAnchor="end">
                {minW.toFixed(0)}
              </SvgText>

              {/* X axis labels: first, middle, last date */}
              {byDateAsc.length > 0 ? (
                <SvgText x="40" y="112" fontSize="7" fill={STONE} textAnchor="start">
                  {fmtDate(byDateAsc[0].log_date)}
                </SvgText>
              ) : null}
              {byDateAsc.length > 2 ? (
                <SvgText x="265" y="112" fontSize="7" fill={STONE} textAnchor="middle">
                  {fmtDate(byDateAsc[Math.floor((byDateAsc.length - 1) / 2)].log_date)}
                </SvgText>
              ) : null}
              {byDateAsc.length > 1 ? (
                <SvgText x="490" y="112" fontSize="7" fill={STONE} textAnchor="end">
                  {fmtDate(byDateAsc[byDateAsc.length - 1].log_date)}
                </SvgText>
              ) : null}
            </Svg>

            {/* Legend */}
            <View style={styles.chartLegendRow}>
              <View style={styles.legendItem}>
                <View style={[styles.legendSwatch, { backgroundColor: BRAND_GREEN }]} />
                <Text style={styles.legendText}>{labels.actualWeight}</Text>
              </View>
              {targetWeight != null ? (
                <View style={styles.legendItem}>
                  <View style={[styles.legendSwatch, { backgroundColor: TARGET_RED }]} />
                  <Text style={styles.legendText}>
                    {labels.target.includes('{{weight}}')
                      ? labels.target.replace('{{weight}}', targetWeight)
                      : `${labels.target} (${targetWeight} kg)`}
                  </Text>
                </View>
              ) : null}
            </View>
          </View>
        ) : null}

        {/* SECTION 5 — VISIT LOG TABLE */}
        <View wrap={false}>
          <Text style={styles.sectionTitle}>{labels.visitHistory}</Text>
          <View style={styles.tableHeader}>
            <Text style={[styles.th, { width: COL.date }]}>{labels.date}</Text>
            <Text style={[styles.th, { width: COL.weight }]}>{labels.weight}</Text>
            <Text style={[styles.th, { width: COL.change }]}>{labels.change}</Text>
            <Text style={[styles.th, { width: COL.waist }]}>Waist</Text>
            <Text style={[styles.th, { width: COL.hips }]}>Hips</Text>
            <Text style={[styles.th, { width: COL.arms }]}>Arms</Text>
            <Text style={[styles.th, { flex: 1 }]}>{labels.notes}</Text>
          </View>

          {tableLogs.map((l, i) => {
            const delta = num(l.weight_delta);
            const noteText = (l.session_notes ?? l.notes ?? '').slice(0, 40);
            return (
              <View key={l.id ?? i} style={[styles.tableRow, i % 2 === 1 && styles.tableRowAlt]}>
                <Text style={[styles.td, { width: COL.date }]}>{fmtDate(l.log_date)}</Text>
                <Text
                  style={[
                    styles.td,
                    { width: COL.weight, fontFamily: 'Helvetica-Bold' },
                  ]}
                >
                  {num(l.weight) != null ? `${l.weight} kg` : '—'}
                </Text>
                <Text
                  style={[
                    styles.td,
                    { width: COL.change },
                    delta != null
                      ? { color: delta < 0 ? LOSS_GREEN : delta > 0 ? GAIN_RED : STONE }
                      : { color: STONE },
                  ]}
                >
                  {delta != null ? `${delta > 0 ? '+' : ''}${delta.toFixed(1)}` : '—'}
                </Text>
                <Text style={[styles.td, { width: COL.waist }]}>{fmtCm(l.waist_cm)}</Text>
                <Text style={[styles.td, { width: COL.hips }]}>{fmtCm(l.hips_cm)}</Text>
                <Text style={[styles.td, { width: COL.arms }]}>{fmtCm(l.arms_cm)}</Text>
                <Text style={[styles.td, { flex: 1 }]}>{noteText || '—'}</Text>
              </View>
            );
          })}

          {truncated ? <Text style={styles.tableNote}>{labels.showingLast}</Text> : null}
        </View>

        {/* SECTION 6 — FOOTER */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>
            {labels.generatedBy} · {generatedDate}
          </Text>
          <Text
            style={styles.footerText}
            render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
          />
        </View>
      </Page>
    </Document>
  );
}
